version: '3.8'

services:
  queuemaster-web:
    build:
      context: ..
      dockerfile: deploy/Dockerfile
    container_name: queuemaster-web
    ports:
      - "80:80"
    restart: always
    networks:
      - queuemaster-network

networks:
  queuemaster-network:
    driver: bridge
